### ISSUE TITLE
Can not get configuration to trigger oauth

### ISSUE THREAD

**Issue by pgordemer** [bitfocus/companion-module-youtube-live#128]
Using 3.4.2 Companion of PI5

debug: Only recent lines are shown here, nothing is persisted
error: Error getting config fields: Call timed out
error: Error getting config fields: Call timed out
error: Module registration failed Error: Call timed out
    at t.IpcWrapper.sendWithCb (/opt/companion/bundled-modules/youtube-live/main.js:2:8131640)
    at /opt/companion/bundled-modules/youtube-live/main.js:2:8124695
error: Error getting config fields: Call timed out
Starting up module class: f
Sentry disabled

**Comment by pgordemer** [comment]
Seems the problem is all related to IPV6. If I disable IPV6, then I get an Auth Key. As soon as I enable IPV6, the integration fails to connect.
